export interface ColorToken {
  name: string;
  cssVar: string;
  tailwind: string;
  light: string;
  dark?: string;
  role: string;
  usage: string;
  editIn: string;
}

export const colorTokens: ColorToken[] = [
  {
    name: 'Background',
    cssVar: '--background',
    tailwind: 'bg-background',
    light: '#f8f8f8',
    dark: '#0f131a',
    role: 'Bazowe tło',
    usage: 'Tło aplikacji, lista katalogów, design system.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Card',
    cssVar: '--card',
    tailwind: 'bg-card',
    light: '#ffffff',
    dark: '#181d25',
    role: 'Tło kart shadcn',
    usage: 'Karty design system page i komponenty Radix/shadcn.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Card foreground',
    cssVar: '--card-foreground',
    tailwind: 'text-card-foreground',
    light: '#262626',
    dark: '#f5f3f0',
    role: 'Tekst na karcie',
    usage: 'Tekst i ikony na tle card.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Popover',
    cssVar: '--popover',
    tailwind: 'bg-popover',
    light: '#ffffff',
    dark: '#181d25',
    role: 'Tło popoverów',
    usage: 'Popovery, dropdowny i menu kontekstowe Radix.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Popover foreground',
    cssVar: '--popover-foreground',
    tailwind: 'text-popover-foreground',
    light: '#262626',
    dark: '#f5f3f0',
    role: 'Tekst w popoverze',
    usage: 'Tekst i ikony na tle popover.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Foreground',
    cssVar: '--foreground',
    tailwind: 'text-foreground',
    light: '#262626',
    dark: '#f5f3f0',
    role: 'Podstawowy tekst',
    usage: 'Domyślny kolor tekstu, nagłówki, aktywne elementy.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Primary',
    cssVar: '--primary',
    tailwind: 'bg-primary text-primary',
    light: '#141414',
    dark: '#f5f3f0',
    role: 'Główna akcja',
    usage: 'Główne przyciski, ring, ciemne akcenty.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Primary foreground',
    cssVar: '--primary-foreground',
    tailwind: 'text-primary-foreground',
    light: '#f8f8f8',
    dark: '#212631',
    role: 'Tekst na primary',
    usage: 'Tekst i ikony na tle primary.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Secondary',
    cssVar: '--secondary',
    tailwind: 'bg-secondary text-secondary',
    light: '#f0f0f0',
    dark: '#272c35',
    role: 'Powierzchnia drugorzędna',
    usage: 'Drugorzędne przyciski, progress, panele pomocnicze.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Secondary foreground',
    cssVar: '--secondary-foreground',
    tailwind: 'text-secondary-foreground',
    light: '#141414',
    dark: '#f5f3f0',
    role: 'Tekst na secondary',
    usage: 'Tekst na tle secondary.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Muted',
    cssVar: '--muted',
    tailwind: 'bg-muted',
    light: '#ebebeb',
    dark: '#272c35',
    role: 'Ciche tło',
    usage: 'Panele techniczne, preview, tabele, podziały informacyjne.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Muted foreground',
    cssVar: '--muted-foreground',
    tailwind: 'text-muted-foreground',
    light: '#595959',
    dark: '#8f96a3',
    role: 'Tekst pomocniczy',
    usage: 'Opisy, meta dane, etykiety drugiego poziomu.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Accent',
    cssVar: '--accent',
    tailwind: 'bg-accent text-accent',
    light: '#ffcd05',
    dark: '#ffcd05',
    role: 'Akcent interakcji',
    usage: 'Akcent tabelaryczny i wybrane elementy aktywne; CTA hero używa primary.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Accent foreground',
    cssVar: '--accent-foreground',
    tailwind: 'text-accent-foreground',
    light: '#141414',
    dark: '#141414',
    role: 'Tekst na accent',
    usage: 'Tekst i ikony na tle accent.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Border',
    cssVar: '--border',
    tailwind: 'border-border',
    light: '#e6e6e6',
    dark: '#303541',
    role: 'Linie i separatory',
    usage: 'Karty, tabele, oddzielenia sekcji, focus context.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Input',
    cssVar: '--input',
    tailwind: 'border-input',
    light: '#d6d6d6',
    dark: '#3d4452',
    role: 'Obramowanie pól',
    usage: 'Pola formularzy i kontrolki.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Ring',
    cssVar: '--ring',
    tailwind: 'ring-ring',
    light: '#141414',
    dark: '#ce853b',
    role: 'Focus ring',
    usage: 'Obrys focus-visible i komponentów Radix/shadcn. Zostaje ciemny dla kontrastu na jasnym tle.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Surface',
    cssVar: '--surface',
    tailwind: 'bg-surface',
    light: '#f2f2f2',
    dark: '#161a22',
    role: 'Powierzchnia katalogowa',
    usage: 'Sekcje i panele katalogu na tle aplikacji.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Surface elevated',
    cssVar: '--surface-elevated',
    tailwind: 'bg-surface-elevated',
    light: '#ffffff',
    dark: '#1d212b',
    role: 'Powierzchnia podniesiona',
    usage: 'Karty, białe panele, ekspozycja zasobów.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'On dark',
    cssVar: '--on-dark',
    tailwind: 'text-on-dark',
    light: '#fafafa',
    dark: '#212631',
    role: 'Tekst na ciemnym tle',
    usage: 'Hero, nakładki, ciemne powierzchnie.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'On dark muted',
    cssVar: '--on-dark-muted',
    tailwind: 'text-on-dark-muted',
    light: '#d0d0d0',
    dark: '#4c5567',
    role: 'Pomocniczy tekst na ciemnym tle',
    usage: 'Drugorzędne opisy w hero i ciemnych panelach.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'On dark subtle',
    cssVar: '--on-dark-subtle',
    tailwind: 'text-on-dark-subtle',
    light: '#9e9e9e',
    dark: '#676f7e',
    role: 'Subtelny tekst na ciemnym tle',
    usage: 'Najcichsze meta dane na ciemnych powierzchniach.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Warm light',
    cssVar: '--warm-light',
    tailwind: 'bg-warm-light',
    light: '#f2eee8',
    dark: '#372e25',
    role: 'Jasne tło ekspozycyjne',
    usage: 'Ciepłe, neutralne tło dla produktu.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Success',
    cssVar: '--success',
    tailwind: 'text-success bg-success',
    light: '#318153',
    dark: '#318153',
    role: 'Status pozytywny',
    usage: 'Zarezerwowane dla statusów i potwierdzeń.',
    editIn: 'src/app/globals.css :root',
  },
  {
    name: 'Info',
    cssVar: '--info',
    tailwind: 'text-info bg-info',
    light: '#227bc3',
    dark: '#227bc3',
    role: 'Status informacyjny',
    usage: 'Zarezerwowane dla komunikatów informacyjnych.',
    editIn: 'src/app/globals.css :root',
  },
  {
    name: 'Warning',
    cssVar: '--warning',
    tailwind: 'text-warning bg-warning',
    light: '#ca8a04',
    dark: '#f59e0b',
    role: 'Status ostrzegawczy',
    usage: 'Komunikaty wymagające uwagi, walidacja niska priorytet, banery info-warning.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Warning foreground',
    cssVar: '--warning-foreground',
    tailwind: 'text-warning-foreground',
    light: '#1a1a1a',
    dark: '#1a1a1a',
    role: 'Tekst na warning',
    usage: 'Tekst i ikony na tle warning.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Destructive',
    cssVar: '--destructive',
    tailwind: 'text-destructive bg-destructive',
    light: '#ef4444',
    dark: '#7f1d1d',
    role: 'Błąd / destrukcja',
    usage: 'Błędy formularzy, alerty i akcje ryzykowne.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Destructive foreground',
    cssVar: '--destructive-foreground',
    tailwind: 'text-destructive-foreground',
    light: '#f8fafc',
    dark: '#f8fafc',
    role: 'Tekst na destructive',
    usage: 'Tekst i ikony na tle destructive.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Hero overlay',
    cssVar: '--hero-overlay',
    tailwind: '—',
    light: '#262626',
    dark: '#0b0e13',
    role: 'Nakładka tonalna hero',
    usage: 'Ciemna nakładka pod tekstem hero katalogu.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Catalog footer background',
    cssVar: '--catalog-footer-background',
    tailwind: 'bg-catalog-footer',
    light: '#f5f5f5',
    dark: '#1e2229',
    role: 'Tło stopki katalogu',
    usage: 'Stopka z linkami do innych katalogów.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Product table header',
    cssVar: '--product-table-header',
    tailwind: 'bg-product-header',
    light: '#a1a1a1',
    dark: '#ffcd05',
    role: 'Nagłówek tabel produktowych',
    usage: 'Nagłówki tabel kodów produktowych.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Product table muted',
    cssVar: '--product-table-muted',
    tailwind: 'bg-product-muted',
    light: '#d9d9d9',
    dark: '#363b45',
    role: 'Tło komórek tabel produktowych',
    usage: 'Techniczne komórki i etykiety w tabelach kodów.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Product table text',
    cssVar: '--product-table-text',
    tailwind: 'text-product-text',
    light: '#7a7a7a',
    dark: '#c1c5cd',
    role: 'Tekst tabel produktowych',
    usage: 'Bazowy tekst w tabelach kodów produktowych.',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Chart 1',
    cssVar: '--chart-1',
    tailwind: 'bg-chart-1 text-chart-1',
    light: '#141414',
    dark: '#f5f3f0',
    role: 'Wykres — seria 1',
    usage: 'Pierwsza seria danych w wykresach (recharts/shadcn chart).',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Chart 2',
    cssVar: '--chart-2',
    tailwind: 'bg-chart-2 text-chart-2',
    light: '#ffcd05',
    dark: '#ffcd05',
    role: 'Wykres — seria 2',
    usage: 'Druga seria danych (akcent METRO).',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Chart 3',
    cssVar: '--chart-3',
    tailwind: 'bg-chart-3 text-chart-3',
    light: '#227bc3',
    dark: '#5aa9d6',
    role: 'Wykres — seria 3',
    usage: 'Trzecia seria danych (info).',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Chart 4',
    cssVar: '--chart-4',
    tailwind: 'bg-chart-4 text-chart-4',
    light: '#318153',
    dark: '#4ea878',
    role: 'Wykres — seria 4',
    usage: 'Czwarta seria danych (success).',
    editIn: 'src/app/globals.css :root + .dark',
  },
  {
    name: 'Chart 5',
    cssVar: '--chart-5',
    tailwind: 'bg-chart-5 text-chart-5',
    light: '#ca8a04',
    dark: '#f59e0b',
    role: 'Wykres — seria 5',
    usage: 'Piąta seria danych (warning).',
    editIn: 'src/app/globals.css :root + .dark',
  },
];
